-- 코드를 입력하세요
SELECT A.AUTHOR_ID AS AUTHOR_ID, A.AUTHOR_NAME AS AUTHOR_NAME,
        B.CATEGORY AS CATEGORY, SUM(B.PRICE * S.SALES) AS TOTAL_SALES
FROM AUTHOR AS A LEFT JOIN BOOK AS B ON A.AUTHOR_ID = B.AUTHOR_ID
    LEFT JOIN BOOK_SALES AS S ON B.BOOK_ID = S.BOOK_ID
WHERE YEAR(S.SALES_DATE) = '2022' AND MONTH(S.SALES_DATE) = '1'
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC;