-- 코드를 입력하세요
WITH TMP AS (
    SELECT C.CAR_ID AS CAR_ID, C.CAR_TYPE AS CAR_TYPE,
           ROUND(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR AS C
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
    ON C.CAR_TYPE = P.CAR_TYPE
    WHERE C.CAR_TYPE IN ('세단','SUV')
    AND P.DURATION_TYPE != '90일 이상'
    AND NOT EXISTS (
        SELECT 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
        WHERE H.CAR_ID = C.CAR_ID
        AND START_DATE <= '2022-11-30'
        AND END_DATE >= '2022-11-1'
    )
)

SELECT CAR_ID, CAR_TYPE, MIN(FEE) AS FEE
FROM TMP
GROUP BY CAR_ID
HAVING MIN(FEE) >= 500000 AND MIN(FEE) < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;