-- 코드를 작성해주세요

WITH FISH_COUNT AS (
    SELECT FISH_TYPE, COUNT(TIME) AS CNT
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)


SELECT C.CNT AS FISH_COUNT, N.FISH_NAME AS FISH_NAME
FROM FISH_COUNT AS C JOIN FISH_NAME_INFO AS N ON C.FISH_TYPE = N.FISH_TYPE
ORDER BY FISH_COUNT DESC;