-- 코드를 입력하세요
WITH USERS AS (SELECT * FROM USER_INFO WHERE YEAR(JOINED) = '2021'),
TOTAL AS (SELECT COUNT(*) AS CNT FROM USERS)

SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, 
    COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT S.USER_ID) / TOTAL.CNT, 1) AS PUCHASED_RATIO
FROM USERS AS U JOIN ONLINE_SALE AS S USING (USER_ID) JOIN TOTAL ON 1 = 1
GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE)
ORDER BY YEAR, MONTH;