-- 코드를 입력하세요
SELECT U.USER_ID AS USER_ID, U.NICKNAME AS NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS B JOIN USED_GOODS_USER AS U ON B.WRITER_ID = U.USER_ID
WHERE B.STATUS = 'DONE'
GROUP BY B.WRITER_ID  HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;

# WITH filteredtable AS (
#     SELECT WRITER_ID, PRICE
#     FROM USED_GOODS_BOARD
#     WHERE STATUS = 'DONE'
# )


# SELECT
#     u.USER_ID, u.NICKNAME, SUM(fb.PRICE) AS TOTAL_SALES
# FROM
#     filteredtable fb
#     INNER JOIN USED_GOODS_USER u
#     ON fb.WRITER_ID = u.USER_ID
# GROUP BY
#     u.USER_ID,
#     u.NICKNAME
# HAVING
#     SUM(fb.PRICE) >= 700000
# ORDER BY
#     TOTAL_SALES ASC;