-- 코드를 작성해주세요

WITH YEAR_GRADE AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT G.SCORE AS SCORE, E.EMP_NO AS EMP_NO, E.EMP_NAME AS EMP_NAME, E.POSITION AS POSITION, E.EMAIL AS EMAIL
FROM HR_EMPLOYEES AS E JOIN YEAR_GRADE AS G ON E.EMP_NO = G.EMP_NO
ORDER BY SCORE DESC LIMIT 1;