-- 코드를 작성해주세요
SELECT CASE
    WHEN (SUM(S.CATEGORY = 'Front End' AND (D.SKILL_CODE & S.CODE) != 0) > 0) AND SUM(S.NAME = 'Python' AND (D.SKILL_CODE & S.CODE) != 0) > 0 THEN "A"
    WHEN SUM(S.NAME = 'C#' AND (D.SKILL_CODE & S.CODE) != 0) > 0 THEN "B"
    WHEN SUM(S.CATEGORY = 'Front End' AND (D.SKILL_CODE & S.CODE) != 0) > 0 THEN "C"
    END AS GRADE, D.ID AS ID, D.EMAIL AS EMAIL
FROM DEVELOPERS AS D, SKILLCODES AS S
GROUP BY ID
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID;